// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WolfAndSheep;

#nullable disable

namespace WolfAndSheep.Migrations
{
    [DbContext(typeof(WolfAndSheepDbContext))]
    partial class WolfAndSheepDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WolfAndSheep.Move", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AfterCol")
                        .HasColumnType("int");

                    b.Property<int>("AfterRow")
                        .HasColumnType("int");

                    b.Property<int>("BeforeCol")
                        .HasColumnType("int");

                    b.Property<int>("BeforeRow")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Moves");
                });
#pragma warning restore 612, 618
        }
    }
}
